# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f9acb84ef8f362eaef94080a6f42fe0b9fef4fd8ad4104eb0e099bd85d1fe0fc09fa7a1cf655338b182ff329ee0d0277a579196ec47087acca1c6bd673b831

test:
  secret_key_base: 988f80f3ade6e465cff8f6c44441136b45b401b04c0693698b5aa0b3d966ac90c5648b54654231a8ef0675551d11822add89337faa1ff20a8a4bf212bd2ad535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
